# Generated by Django 2.1b1 on 2018-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
